---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: amdocs
    project: "shoppingcart-experience"
    microservice: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": {{ .Values.jobs.configureThirdPartiesPersistent }},post-delete
    "helm.sh/hook-weight": "-10"
  name: "{{.Values.jobs.secret.name}}"
type: '{{.Values.jobs.secret.type}}'
data:
  {{ if .Values.jobs.secret.dockerconfigjson }}
  .dockerconfigjson: {{.Values.jobs.secret.dockerconfigjson}}
  {{ else }}
  .dockerconfigjson: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
