---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: amdocs
    project: "shoppingcart-experience"
    microservice: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: '{{.Values.secret.name}}'
type: '{{.Values.secret.type}}'
data:
  {{ if .Values.secret.snapshotToken }}
  .dockerconfigjson: {{.Values.secret.snapshotToken}}
  {{ else }}
  .dockerconfigjson: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  