---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
  labels:
    provider: amdocs
    project: "shoppingcart-experience"
    microservice: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    expose: "{{.Values.service.expose}}"
    monitored: "prometheus"
    monitoring: "prometheus"
  name: "shoppingcart-experience-service"
spec:
  ports:    
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  - name: "metrics"
    port: 5555
    targetPort: "metrics"
  {{if .Values.jacoco.enabled}}
  - name: "jacoco"
    port: 6300
    protocol: "TCP"
  {{end}}
  selector:
    provider: amdocs
    project: "shoppingcart-experience"
    microservice: {{ template "name" . }}
    release: "{{ .Release.Name }}"
  type: "{{.Values.service.serviceType}}"

